### ISSUE TITLE
Helen hmap and train details

### ISSUE THREAD

**Issue by cffocus** [cs-giung/FSRNet-pytorch#1]
Hi, I am currently reproducing the FSRNet and found your code very helpful. However, I am wondering whether your current model trained based on celeb without hmaps?

**Comment by cs-giung** [comment]
I used CelebAMask-HQ dataset with only parsing map to get `e099_psnr22.53.pth`. If you want to use both parsing-map and landmark-heatmap, you should get the facial landmark information yourself (since the CelebAMask-HQ does not provide landmark annotations).
