### ISSUE TITLE
Helen dataset

### ISSUE THREAD

**Issue by yangyingni** [cs-giung/FSRNet-pytorch#2]
I can't download Helen dataset fromyour link,can you share me one?My e-mail is 2676426668@qq.com,thank your work very much.

**Comment by cs-giung** [comment]
oh... their link is dead, and unfortunately I don't have Helen dataset now. So you'd better wait for their link to be restored, or use another dataset (i.e. celeb).

**Comment by yangyingni** [comment]
Oh,my error.The label pictures shows like black,how should i detect only face labels?The same as below.
&nbsp;




Thank you for your reply,I have CelebaHQ earlier,and want to have another database.I do have a question about Helen dataset ,can you tell me?The pictures and labels pictures contains not only face but bodys,like pictures below.Should i detect this two faces together?Will the faces cut share the same place? Thank you.


&nbsp;
------------------ 原始邮件 ------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 中午1:56
收件人:&nbsp;"cs-giung/FSRNet-pytorch"<FSRNet-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"泱渶"<2676426668@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cs-giung/FSRNet-pytorch] Helen dataset (#2)




oh... their link is dead, and unfortunately I don't have Helen dataset now. So you'd better wait for their link to be restored, or use another dataset (i.e. celeb).

**Comment by yangyingni** [comment]
Thank you for your reply,I have CelebaHQ earlier,and want to have another database.I do have a question about Helen dataset ,can you tell me?The pictures and labels pictures contains not only face but bodys,like pictures below.Should i detect this two faces together?Will the faces cut share the same place? Thank you.


&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 中午1:56
收件人:&nbsp;"cs-giung/FSRNet-pytorch"<FSRNet-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"泱渶"<2676426668@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cs-giung/FSRNet-pytorch] Helen dataset (#2)




oh... their link is dead, and unfortunately I don't have Helen dataset now. So you'd better wait for their link to be restored, or use another dataset (i.e. celeb).

**Comment by yangyingni** [comment]
> oh... their link is dead, and unfortunately I don't have Helen dataset now. So you'd better wait for their link to be restored, or use another dataset (i.e. celeb).

Thank you for your reply,i have celebaHQ earlier and i wang to have another dataset.I do have a question about how to get only faces and labels on Helen,can you tell me?Helen dataset has not only faces but also body,and the size are all different,also do the labels.Thank you.

**Comment by cs-giung** [comment]
The authors said:
> We coarsely crop the training images according to their face regions and resize to 128x128 without any pre-alignment operation.

And Helen dataset provides landmark annotations, so you can get a rough area of the face based on it. I cropped the square area as follows:

* https://github.com/cs-giung/FSRNet-pytorch/blob/master/datasets/helen.py#L117
  ```python
  # crop & resize
  face_img, x1, y1 = self._crop_face_coarsely(image, lmark)
  image_lr = face_img.resize(self.size_lr, Image.BICUBIC)
  image_lr = image_lr.resize(self.size_hr, Image.BICUBIC)
  image_hr = face_img.resize(self.size_hr, Image.BICUBIC)
  ```

* https://github.com/cs-giung/FSRNet-pytorch/blob/master/datasets/helen.py#L91
  ```python
  def _crop_face_coarsely(self, image, lmark):
      xs = [e[0] for e in lmark]
      ys = [e[1] for e in lmark]
      cx, cy = (sum(xs) / len(xs)), (sum(ys) / len(ys))
      w, h = (max(xs) - min(xs)), (max(ys) - min(ys))
      x1 = max(0, int(cx-w))
      y1 = max(0, int(cy-h))
      x2 = min(int(cx+w), image.size[0])
      y2 = min(int(cy+h), image.size[1])
      img = image.crop((x1, y1, x2, y2))
      return img, x1, y1
  ```

**Comment by yangyingni** [comment]
Thank you,i will read this carefully.Can i directly use helen dataset by this link.
http://pages.cs.wisc.edu/~lizhang/projects/face-parsing/




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 下午2:55
收件人: "cs-giung/FSRNet-pytorch"<FSRNet-pytorch@noreply.github.com&gt;; 
抄送: "泱渶"<2676426668@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cs-giung/FSRNet-pytorch] Helen dataset (#2)




The authors said:
  
We coarsely crop the training images according to their face regions and resize to 128x128 without any pre-alignment operation.
  
And Helen dataset provides landmark annotations, so you can get a rough area of the face based on it. I cropped the square area as follows:
  
 
https://github.com/cs-giung/FSRNet-pytorch/blob/master/datasets/helen.py#L117
 # crop &amp; resize face_img, x1, y1 = self._crop_face_coarsely(image, lmark) image_lr = face_img.resize(self.size_lr, Image.BICUBIC) image_lr = image_lr.resize(self.size_hr, Image.BICUBIC) image_hr = face_img.resize(self.size_hr, Image.BICUBIC)
 
 
 
https://github.com/cs-giung/FSRNet-pytorch/blob/master/datasets/helen.py#L91
 def _crop_face_coarsely(self, image, lmark):     xs = [e[0] for e in lmark]     ys = [e[1] for e in lmark]     cx, cy = (sum(xs) / len(xs)), (sum(ys) / len(ys))     w, h = (max(xs) - min(xs)), (max(ys) - min(ys))     x1 = max(0, int(cx-w))     y1 = max(0, int(cy-h))     x2 = min(int(cx+w), image.size[0])     y2 = min(int(cy+h), image.size[1])     img = image.crop((x1, y1, x2, y2))     return img, x1, y1

**Comment by cs-giung** [comment]
It will be possible if it has the same name and directory structure as original Helen dataset (see `./datasets/_annos/list_annos_*.txt` and [`./datasets/README.md`](https://github.com/cs-giung/FSRNet-pytorch/blob/master/datasets/README.md))

**Comment by yangyingni** [comment]
Thank you very much，it seems that you just used landmark but not parsing?Sorry to have so many questions，I am new to Helen.



---Original---

**Comment by cs-giung** [comment]
Helen dataset provides 194 landmark points, which can be used as a parsing map as well as heatmap by connecting the dots and coloring them.
https://github.com/cs-giung/FSRNet-pytorch/blob/master/datasets/helen.py#L69

However, if you want to use a more accurate parsing map, consider a different approach (use the parsing map released by someone, or obtain the parsing map on your own).
