### ISSUE TITLE
Discussion on training details

### ISSUE THREAD

**Issue by yangyingni** [cs-giung/FSRNet-pytorch#3]
Thank you for your work very much.I read your code and have some questions about training,can you please tell me.
1.  Has PriorEstimationNetwork  been trained in advance?I can't from from your code.           
2. The parameters in the PriorEstimationNetwork will change or not?            
3. Have the images of training prior network and training fsrnet normalized?
Thank you for your help.

**Comment by cs-giung** [comment]
1. In FSRNet, all sub-networks (i.e. Coarse SR Network, Fine SR Network, Prior Estimation Network, Fine SR Decoder) are trained in end-to-end manner. See
    * https://github.com/cs-giung/FSRNet-pytorch#overview

    * https://github.com/cs-giung/FSRNet-pytorch/blob/master/train.py#L83

2. Prior Estimation Network is trained in the above process.

3. All images (including heat-maps and parsing-maps) are normalized in this code. See
    * https://github.com/cs-giung/FSRNet-pytorch/blob/master/train.py#L68

    * https://github.com/cs-giung/FSRNet-pytorch/blob/master/train.py#L74

    * https://github.com/cs-giung/FSRNet-pytorch/blob/master/utils.py#L11

    Also, predicted results should be denormalized to get valid images. See
    * https://github.com/cs-giung/FSRNet-pytorch/blob/master/demo.py#L44

    * https://github.com/cs-giung/FSRNet-pytorch/blob/master/utils.py#L19

**Comment by yangyingni** [comment]
Thank you very much,it's kind of you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 下午4:22
收件人:&nbsp;"cs-giung/FSRNet-pytorch"<FSRNet-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"泱渶"<2676426668@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cs-giung/FSRNet-pytorch] Discussion on training details (#3)





  
 
In FSRNet, all sub-networks (i.e. Coarse SR Network, Fine SR Network, Prior Estimation Network, Fine SR Decoder) are trained in end-to-end manner. See
  
https://github.com/cs-giung/FSRNet-pytorch#overview
 
https://github.com/cs-giung/FSRNet-pytorch/blob/master/train.py#L83
  
 
 
Prior Estimation Network is trained in the above process.
 
 
 
All images (including heat-maps and parsing-maps) are normalized in this code. See
  
https://github.com/cs-giung/FSRNet-pytorch/blob/master/train.py#L68
 
https://github.com/cs-giung/FSRNet-pytorch/blob/master/train.py#L74
 
https://github.com/cs-giung/FSRNet-pytorch/blob/master/utils.py#L11
  
Also, predicted results should be denormalized to get valid images. See
  
https://github.com/cs-giung/FSRNet-pytorch/blob/master/demo.py#L44
 
https://github.com/cs-giung/FSRNet-pytorch/blob/master/utils.py#L19
