### ISSUE TITLE
Question about training dataset

### ISSUE THREAD

**Issue by yangyingni** [cs-giung/FSRNet-pytorch#6]
Hello,I was also using Celeba-HQ  for training,the same size as you,16px and 128px.Is the 16px Celeba-HQ quite dataset quite low resolution?I think so,but a little doubt.I used SRResnet x8 to train it,with same dataset,get PSNR more than 30?And the results seems to be better than FSRNET?Is it right to deal with dataset?

**Comment by cs-giung** [comment]
1. To the best of my knowledge, 16x16 is quite low resolution (it seems to me that 8x8 is the lowest, in practical).

2. The following FSNR values are given in the FSRNet paper. The results claim that FSRNet is superior to SRResNet (I'm afraid I haven't tested it myself, so I can't tell you anything. However, the fact that PSNR is over 30 in your result is doubtful to me).
    | - | Bicubic | SRResNet | FSRNet |
    | - | :-: | :-: | :-: |
    | Helen | 23.69 | 25.30 | 25.87 |
    | celebA | 23.75 | 25.82 | 26.31 |

**Comment by yangyingni** [comment]
> 1. To the best of my knowledge, 16x16 is quite low resolution (it seems to me that 8x8 is the lowest, in practical).
> 2. The following FSNR values are given in the FSRNet paper. The results claim that FSRNet is superior to SRResNet (I'm afraid I haven't tested it myself, so I can't tell you anything. However, the fact that PSNR is over 30 in your result is doubtful to me).
>    
>    
>    
>    -
>    Bicubic
>    SRResNet
>    FSRNet
>    
>    
>    
>    
>    Helen
>    23.69
>    25.30
>    25.87
>    
>    
>    celebA
>    23.75
>    25.82
>    26.31

I used srresnet in mmsr,it shows that it's psnr was higher than 30,and I was doubt. But it has quite good result. For examlpe
![qxlarge-dsc-56CE00CE1FDDFECABE1A42E7E7579E12](https://user-images.githubusercontent.com/35161397/78472465-8c767180-776b-11ea-9625-0e6e3d0aa898.png).

**Comment by cs-giung** [comment]
Interesting! Is this really 16x16 to 128x128? Now I think it would be better to compare FSRNet performance in the same environment (it means, your mmsr platform).

**Comment by yangyingni** [comment]
I feel quite terrible now，Do you mind contact me QQ,2676426668

**Comment by cs-giung** [comment]
Sorry. It is difficult to use QQ to me.

Please feel free to contact me via this board or giung@korea.ac.kr.
Thank you.

**Comment by yangyingni** [comment]
Sorry to reply you so late,thank you very much.
