### ISSUE TITLE
PSNR

### ISSUE THREAD

**Issue by mhu1515** [cs-giung/FSRNet-pytorch#7]
Hi, I ran your code with  CelebAMask-HQ dataset. But I only got an 18.33 of  PSNR. Do you know the reason?

**Comment by cs-giung** [comment]
Do you get the same values when you run `demo.py`? If you use a given `e099_psnr22.53.pth` file, you should get the same result as the following:
![](https://github.com/cs-giung/FSRNet-pytorch/raw/master/_md/demo1.png)

**Comment by mhu1515** [comment]
I get the same values when I run demo.py. But  I only got an 18.33 of PSNR when I run the train.py and trainGAN.py. I can't get the same 22.53 of psnr with the given e099_psnr22.53.pth .  I want to know if you have done additional processing on the data？ Or there are any other reasons.







At 2020-05-25 18:27:32, "cs-giung" <notifications@github.com> wrote:

Do you get the same values when you run demo.py? If you use a given e099_psnr22.53.pth file, you should get the same result as the following:

**Comment by mhu1515** [comment]
Can you provide your parsing map for CelebAMask-HQ and Helen dataset?
