### ISSUE TITLE
train result

### ISSUE THREAD

**Issue by KushinaYu** [cs-giung/FSRNet-pytorch#8]
Hi! I ran the train.py with CelebAMask dataset but only get a 19.47 of PSNR. Did you use the landmark information of the  CelebAMask dataset? Or made some special process with the dataset?

**Comment by cs-giung** [comment]
I only used parsing map for training. Please make sure that you have reconstructed the CELEB_ROOT directory as follows:

```
CELEB_ROOT/
|
+-- CelebA-HQ-img/
|   +-- 0.jpg
|   +-- 1.jpg
|   +-- (...)
|
+-- CelebAMask-HQ-mask-anno/
|   +-- merged/
|         +-- 00000_hair.png
|         +-- 00000_l_brow.png
|         +-- (...)
|
+-- train_fileList.txt
+-- test_fileList.txt
```

**Comment by cs-giung** [comment]
Thanks to you, I realized that I wrote the wrong directory...
(https://github.com/cs-giung/FSRNet-pytorch/tree/master/datasets)

BEFORE UPDATE:
```
root/
+-- CelebA-HQ-img/
|   +-- { *.jpg }
|
+-- CelebAMask-HQ-mask-anno/
|   +-- { *.png }
|
+-- train_fileList.txt
+-- test_fileList.txt
```
AFTER UPDATE:
```
root/
+-- CelebA-HQ-img/
|   +-- { *.jpg }
|
+-- CelebAMask-HQ-mask-anno/
|   +-- merged/
|       +-- { *.png }
|
+-- train_fileList.txt
+-- test_fileList.txt
```

**Comment by KushinaYu** [comment]
Thanks for your reply. Do you mean that you get a 22.53 of psnr by only using the merged parsing map?------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;cs-giung&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月2日(星期二) 晚上7:46
收件人:&nbsp;&quot;cs-giung/FSRNet-pytorch&quot;<FSRNet-pytorch@noreply.github.com&gt;;
抄送:&nbsp;&quot;Betty Hu&quot;<2435142508@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cs-giung/FSRNet-pytorch] train result (#8)

**Comment by cs-giung** [comment]
Yes, I did.
